#!/bin/env bash

# default terminal
DEF_TERM="alacritty --config-file $HOME/.config/qtile/alacritty/alacritty.yml"

# default editor
DEF_EDITOR="vim"

# colors and font
BG="#0F131F"
FG="#82dbf4"
ALT_BG="#5b99aa"
FONT="Source Code Pro Medium:size=12"

# list of configs
declare -a options=(
"Alacritty - $HOME/.config/qtile/alacritty/alacritty.yml"
"Alacritty (Fonts) - $HOME/.config/qtile/alacritty/fonts.yml"
"Autostart - $HOME/.config/qtile/scripts/autostart.sh"
"Feh (Wallpaper Background) - $HOME/.config/qtile/scripts/.fehbg"
"Fish - $HOME/.config/fish/config.fish"
"Picom - $HOME/.config/picom.conf"
"Qtile - $HOME/.config/qtile/config.py"
"Vim - $HOME/.vimrc"
)

# creates the menu
choice=$(printf '%s\n' "${options[@]}" | sort -u | dmenu -c -i -l 10 -nb "$BG" -nf "$FG" -sb "$ALT_BG" -sf "$FG" -fn "$FONT" -p 'Edit Config:')

# opens the selected config file with vim
# exits otherwise
if [ "$choice" ]; then
    cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
    $DEF_TERM -e $DEF_EDITOR "$cfg"

else
    echo "Exiting..."; exit 1
fi


